"""Scaffold — generates a new agent's starting files in seconds instead of
hand-wiring AgentConfig, a prompt file, and a topology from scratch. This is
what actually moves build time from days to hours: the architecture makes an
agent *possible* to build quickly, this module makes it *fast* to start.

    python -m agent_foundry.scaffold sales_agent --topology single --tools lookup_lead,send_email

writes prompts/sales_agent.md and agents/sales_agent.py — a runnable script with
TODOs marking the only things you actually need to fill in: the prompt's content
and each tool function's body. Everything else (gateways, guardrails, eval,
runtime, tracer) is already wired.
"""
from __future__ import annotations

import argparse
import os

_PROMPT_TEMPLATE = """You are {title}.

TODO: describe this agent's job, tone, and what it should refuse to do.

To use a tool, reply with exactly:
CALL <tool_name> {{"arg": "value"}}

Tools:
{tool_lines}
"""

_TOOL_STUB_TEMPLATE = '''

def {tool_name}(TODO_arg: str) -> str:
    """TODO: describe what {tool_name} does — this becomes its schema description."""
    raise NotImplementedError("fill in {tool_name}")
'''

_AGENT_TEMPLATE = '''"""{title} — generated by agent_foundry.scaffold.

Fill in the TODOs below (tool bodies + prompts/{name}.md), then run:
    export ANTHROPIC_API_KEY=...
    python agents/{name}.py
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent_foundry.contracts import Identity, Policy, ToolSpec
from agent_foundry.eval import EvalHarness
from agent_foundry.guardrails import GuardrailEngine
from agent_foundry.llm_gateway import AnthropicProvider, LLMGateway
from agent_foundry.observability import Tracer
from agent_foundry.orchestration import build_agent_graph
from agent_foundry.prompts import PromptLibrary
from agent_foundry.runtime import RunBudget
from agent_foundry.tools_gateway import ToolRegistry
from agent_foundry.ui.console import chat_loop
{tool_stubs}

def main() -> None:
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("set ANTHROPIC_API_KEY to run this agent")

    # --- TODO: who is this agent, what can it do, what can't it do ---
    identity = Identity(id="{name}-1", tenant_id="TODO-your-tenant")
    tools = ToolRegistry()
{tool_registrations}
    policy = Policy(
        allowed_tools=frozenset({{{tool_names}}}),
        max_cost_usd_per_thread=1.0,
        max_steps_per_thread=15,
        requires_approval=frozenset(),  # TODO: name any tool that needs a human before it runs
    )

    thread_id = "{name}-demo"
    prompts = PromptLibrary(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "prompts"))
    graph = build_agent_graph(
        system_prompt=prompts.get("{name}"),
        llm=LLMGateway(provider=AnthropicProvider()),
        tools=tools,
        guardrails=GuardrailEngine(policy),
        eval_harness=EvalHarness(),
        identity=identity,
        policy=policy,
        budget=RunBudget(policy),
        tracer=Tracer(thread_id),
    )
    chat_loop(graph, thread_id=thread_id)


if __name__ == "__main__":
    main()
'''


def create_agent(name: str, *, directory: str = ".", topology: str = "single", tools: list[str] | None = None) -> dict[str, str]:
    """Writes prompts/<name>.md and agents/<name>.py under `directory`. Returns the
    paths written. `topology` is currently informational (single-agent template);
    for supervisor/swarm/etc., copy this file's AGENT_TEMPLATE as a starting point
    — the four-line difference is which build_*_graph you call in orchestration.py."""
    tools = tools or []
    title = name.replace("_", " ").replace("-", " ").title()

    tool_lines = "\n".join(f"- {t}(...)" for t in tools) or "(none yet — TODO: add some)"
    prompts_dir = os.path.join(directory, "prompts")
    os.makedirs(prompts_dir, exist_ok=True)
    prompt_path = os.path.join(prompts_dir, f"{name}.md")
    with open(prompt_path, "w") as f:
        f.write(_PROMPT_TEMPLATE.format(title=title, tool_lines=tool_lines))

    tool_stubs = "".join(_TOOL_STUB_TEMPLATE.format(tool_name=t) for t in tools)
    tool_registrations = "".join(
        f'    tools.register(ToolSpec("{t}", "TODO: describe {t}", {{}}, {t}))\n' for t in tools
    ) or "    # TODO: tools.register(ToolSpec(...))\n"
    tool_names = ", ".join(f'"{t}"' for t in tools)

    agents_dir = os.path.join(directory, "agents")
    os.makedirs(agents_dir, exist_ok=True)
    agent_path = os.path.join(agents_dir, f"{name}.py")
    with open(agent_path, "w") as f:
        f.write(_AGENT_TEMPLATE.format(
            title=title, name=name, tool_stubs=tool_stubs,
            tool_registrations=tool_registrations, tool_names=tool_names,
        ))

    return {"prompt": prompt_path, "agent": agent_path}


def _main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold a new Agent Foundry agent.")
    parser.add_argument("name", help="snake_case agent name, e.g. sales_agent")
    parser.add_argument("--directory", default=".", help="project root to write prompts/ and agents/ into")
    parser.add_argument("--topology", default="single", choices=["single"], help="currently only 'single' is templated")
    parser.add_argument("--tools", default="", help="comma-separated tool names, e.g. lookup_lead,send_email")
    args = parser.parse_args()

    tools = [t.strip() for t in args.tools.split(",") if t.strip()]
    paths = create_agent(args.name, directory=args.directory, topology=args.topology, tools=tools)
    print(f"wrote {paths['prompt']}")
    print(f"wrote {paths['agent']}")
    print(f"next: fill in the TODOs, set ANTHROPIC_API_KEY, then run python {paths['agent']}")


if __name__ == "__main__":
    _main()
